// One Jev call per passage: p(ai) from a two-way choice question.
// The server and eval/ share this module, so a variant and threshold tuned in eval are the ones
// that run live. The variant id is part of the cache key: never change a variant in place, add one.
import crypto from 'node:crypto';
import { systemOne } from './typesafe.mjs';

export const MAX_CHARS = 4000;

const EN_INSTRUCTIONS = 'A passage of text found on a web page. Was it written by a human, or generated by an AI language model (ChatGPT, Claude, Gemini etc.)? Judge style, not topic.';
const EN_CRITERIA = {
  human: 'Written by a person: idiosyncratic, uneven, specific, personal voice, typos or odd phrasing',
  ai: 'Generated by an AI model: polished generic phrasing, stock transitions, balanced lists, hedged summaries, "delve", "landscape", "it\'s worth noting", tidy three-part structure',
};

const NO_INSTRUCTIONS = 'Et tekstavsnitt fra en norsk nettside. Er det skrevet av et menneske, eller generert av en AI-språkmodell (ChatGPT, Claude, Gemini o.l.)? Vurder språk og stil, ikke tema.';
const NO_CRITERIA = {
  human: 'Skrevet av et menneske: egen stemme, ujevn rytme, konkrete detaljer, dialekt- eller muntlige former, forkortelser, slang, skrivefeil eller litt klønete setninger. Saklig norsk med konkrete navn, tall og steder kan også være menneskeskrevet',
  ai: 'Generert av AI: glatt og feilfri men generisk bokmål, oversatt-fra-engelsk-preg ("i dagens raskt skiftende verden", "spiller en avgjørende rolle", "det er verdt å merke seg", "ikke bare ... men også", "dykke ned i", "navigere", "sømløs", "helhetlig"), tretrinns oppramsinger, pene overganger og en oppsummerende avslutning ("Kort sagt", "Alt i alt", "Til syvende og sist")',
};

const choice = (instructions, criteria) => ({ origin: { type: 'choice', instructions, criteria } });

// Rough language guess from function words; good enough to route bokmål/nynorsk vs English.
const NO_WORDS = new Set('og ikke ikkje det som jeg eg på er av med til har å men kan vil eller også når fra frå hva kva dette jo bare berre vi dei de seg han hun ho'.split(' '));
const EN_WORDS = new Set('the and is of to in that it with was for are this but have not you on be as at'.split(' '));
export function isNorwegian(text) {
  let no = 0, en = 0;
  for (const w of text.toLowerCase().match(/[a-zæøå]+/g) || []) {
    if (NO_WORDS.has(w)) no++;
    else if (EN_WORDS.has(w)) en++;
  }
  return no > en || (/[æøå]/i.test(text) && no >= en);
}

// Each variant maps a passage to Jev's { state, questions }.
export const VARIANTS = {
  // v1: one English question for every language (live 2026-09-23).
  v1: (text) => ({ state: { passage: text }, questions: choice(EN_INSTRUCTIONS, EN_CRITERIA) }),
  // v2, v3: tried and rejected 2026-09-23. Naming Norwegian tells in the question lowered
  // Norwegian hits (tune split: v1 16%, v2 12%, v3 4%). A lower Norwegian threshold works instead.
  // v2: v1 with Norwegian tells appended to the English criteria.
  v2: (text) => ({
    state: { passage: text },
    questions: choice(EN_INSTRUCTIONS, {
      human: `${EN_CRITERIA.human}. Norwegian: dialect or colloquial forms, abbreviations, slang, concrete local detail`,
      ai: `${EN_CRITERIA.ai}. Norwegian: smooth generic bokmål that reads translated from English ("i dagens raskt skiftende", "spiller en avgjørende rolle", "det er verdt å merke seg", "ikke bare ... men også", "dykke ned i", "Kort sagt", "Alt i alt")`,
    }),
  }),
  // v3: Norwegian passages get a Norwegian question with Norwegian tells; English stays v1.
  v3: (text) => (isNorwegian(text)
    ? { state: { passage: text, language: 'norsk' }, questions: choice(NO_INSTRUCTIONS, NO_CRITERIA) }
    : VARIANTS.v1(text)),
};

export const ACTIVE = process.env.SLOPMARK_VARIANT || 'v1';

export const normalize = (text) => text.replace(/\s+/g, ' ').trim().slice(0, MAX_CHARS);

// v1 keys keep their original "v1\n" prefix, so the live cache survives this refactor.
export const cacheKey = (text, variant = ACTIVE) =>
  crypto.createHash('sha256').update(`${variant}\n${normalize(text)}`).digest('hex');

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Returns { p_ai, model }. Retries 429/5xx/timeouts with backoff.
export async function classify(text, { variant = ACTIVE, retries = 3 } = {}) {
  const build = VARIANTS[variant];
  if (!build) throw new Error(`unknown variant ${variant}`);
  for (let attempt = 0; ; attempt++) {
    try {
      const r = await systemOne(build(normalize(text)));
      const p = r.answers?.origin?.probabilities?.ai;
      if (typeof p !== 'number') throw new Error('typesafe: no probability in answer');
      return { p_ai: p, model: r.model };
    } catch (e) {
      const retryable = !e.status || e.status === 429 || e.status >= 500;
      if (!retryable || attempt >= retries) throw e;
      await sleep(1000 * 2 ** attempt);
    }
  }
}
