// One Jev call per passage: p(ai) from a two-way choice question.
// The server and eval/ share this module, so a threshold tuned in eval is the one that runs live.
import crypto from 'node:crypto';
import { systemOne } from './typesafe.mjs';

export const QUESTION_VERSION = 1; // bump when QUESTIONS change; it is part of the cache key
export const MAX_CHARS = 4000;

export const QUESTIONS = {
  origin: {
    type: 'choice',
    instructions: 'A passage of text found on a web page. Was it written by a human, or generated by an AI language model (ChatGPT, Claude, Gemini etc.)? Judge style, not topic.',
    criteria: {
      human: 'Written by a person: idiosyncratic, uneven, specific, personal voice, typos or odd phrasing',
      ai: 'Generated by an AI model: polished generic phrasing, stock transitions, balanced lists, hedged summaries, "delve", "landscape", "it\'s worth noting", tidy three-part structure',
    },
  },
};

export const normalize = (text) => text.replace(/\s+/g, ' ').trim().slice(0, MAX_CHARS);

export const cacheKey = (text) =>
  crypto.createHash('sha256').update(`v${QUESTION_VERSION}\n${normalize(text)}`).digest('hex');

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Returns { p_ai, model }. Retries 429/5xx/timeouts with backoff.
export async function classify(text, { retries = 3 } = {}) {
  for (let attempt = 0; ; attempt++) {
    try {
      const r = await systemOne({ state: { passage: normalize(text) }, questions: QUESTIONS });
      const p = r.answers?.origin?.probabilities?.ai;
      if (typeof p !== 'number') throw new Error('typesafe: no probability in answer');
      return { p_ai: p, model: r.model };
    } catch (e) {
      const retryable = !e.status || e.status === 429 || e.status >= 500;
      if (!retryable || attempt >= retries) throw e;
      await sleep(1000 * 2 ** attempt);
    }
  }
}
